version: "3.7"
services:
  mysql-server:
    build:
        dockerfile: ./config/docker/mysql.Dockerfile
        context: .
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports: 
      - "33060:3306"
volumes:
  mysql-data: