version: "3.8"
services:
  database:
    image: dajobe/hbase
    ports:  
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
volumes:
    hbase_data:
    hbase_zookeeper_data: