version: "3.7"
services:
  mysql-source:
    build:
        dockerfile: ./config/docker/mysql-source.Dockerfile
        context: .
    environment:
      MYSQL_ROOT_PASSWORD: secret
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - mysql-source-data:/var/lib/mysql
    ports: 
      - "33060:3306"
  mysql-target:
    build:
        dockerfile: ./config/docker/mysql-target.Dockerfile
        context: .
    environment:
      MYSQL_ROOT_PASSWORD: secret
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
      - mysql-target-data:/var/lib/mysql
    ports: 
      - "33061:3306"
volumes:
  mysql-source-data:
  mysql-target-data: